apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s_pipeline
  labels:
    app: k8s_pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s_pipeline
  template:
    metadata:
      labels:
        app: k8s_pipeline
    spec:
      containers:
      - name: myjavaapp-container
        image: admin9666/k8s_pipeline:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
