apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spipeline
  labels:
    app: k8spipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8spipeline
  template:
    metadata:
      labels:
        app: k8spipeline
    spec:
      containers:
      - name: myjavaapp-container
        image: admin9666/k8_spipeline:16
        ports:
        - containerPort: 8080
