apiVersion: v1
kind: Service
metadata:
  name: k8spipeline
  labels:
    app: k8spipeline    
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
    app: k8spipeline
