apiVersion: v1
kind: Service
metadata:
  name: k8s_pipeline
  labels:
    app: k8s_pipeline    
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
    app: k8s_pipeline
